# Generated by Django 5.0.6 on 2024-05-27 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField()),
                ('taskstatus', models.CharField(choices=[('applied', 'Applied'), ('processing', 'Processing'), ('completed', 'Completed')], default='applied', max_length=11)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('updatedon', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2024, 6, 26, 5, 42, 51, 8805))),
                ('completed_on', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='Medium', max_length=10)),
            ],
        ),
    ]
