# Generated by Django 5.0.6 on 2024-05-27 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_application', '0002_taskmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 5, 44, 43, 621430)),
        ),
    ]
