# Generated by Django 5.0.6 on 2024-05-27 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_application', '0004_taskmodel_username_alter_taskmodel_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 9, 49, 15, 933289)),
        ),
    ]
