# Generated by Django 5.0.6 on 2024-05-27 09:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_application', '0005_alter_taskmodel_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='task_assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 9, 55, 0, 457120)),
        ),
    ]
